import { sql } from "drizzle-orm";
import { customType, timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * Primary keys are UUIDv7, generated by PostgreSQL 18. They are
 * time-ordered, so new rows land at the end of B-tree indexes.
 */
export const id = () =>
  uuid("id")
    .primaryKey()
    .default(sql`uuidv7()`);

/** `timestamptz`, stored in UTC. */
export const timestamptz = (name: string) =>
  timestamp(name, { withTimezone: true, mode: "date" });

export const createdAt = () => timestamptz("created_at").notNull().defaultNow();

/** Kept current by the ORM on every update, using the database clock. */
export const updatedAt = () =>
  timestamptz("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdateFn(() => sql`now()`);

/** Raw bytes: token hashes and file digests. */
export const bytea = customType<{ data: Buffer; driverData: Buffer }>({
  dataType: () => "bytea",
});

/** A full-text search document, always generated by the database. */
export const tsvector = customType<{ data: string }>({
  dataType: () => "tsvector",
});
