/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/customer/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description Starts a new customer session in an HttpOnly cookie and returns the same body as `me`. A wrong password, an unknown email and a guest without a password all get the same 401.
         */
        post: operations["CustomerAuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/customer/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start registration
         * @description Takes only an email and always answers 202. The address gets a verification link, or a reminder to sign in if it already has an account. The password is chosen after the link proves the inbox is yours, so nobody can set one for someone else's address.
         */
        post: operations["CustomerAuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/customer/signup/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish registration from the emailed link
         * @description Sets the first password and display name, verifies the email and signs in. Tickets raised earlier as a guest with this email are already in the account.
         */
        post: operations["CustomerAuthController_completeSignup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/customer/guest-access/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for a new link to a ticket
         * @description Always answers 202. If the email and ticket reference match, a fresh access link is emailed.
         */
        post: operations["CustomerAuthController_requestGuestLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/customer/guest-access/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a ticket from an emailed link
         * @description Exchanges the token from the link's URL fragment for a guest session that can see that one ticket.
         */
        post: operations["CustomerAuthController_exchangeGuestLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/customer/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Revokes this session and clears its cookies.
         */
        post: operations["CustomerAuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/customer/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in customer
         * @description For a guest session, `guestTicketId` names the one ticket it can see.
         */
        get: operations["CustomerAuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/staff/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description Starts a new staff session in an HttpOnly cookie and returns the same body as `me`. A deactivated agent, or one who hasn't accepted their invite, gets the same 401 as a wrong password.
         */
        post: operations["StaffAuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/staff/invite/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept an invite
         * @description Sets the invited agent's first password from the emailed link and signs them in. The link works once, and only for an active agent without a password.
         */
        post: operations["StaffAuthController_acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/staff/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Revokes this session and clears its cookies.
         */
        post: operations["StaffAuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/staff/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in agent, with their role and permissions */
        get: operations["StaffAuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description The process is running and can answer. Checks no dependencies.
         */
        get: operations["HealthController_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Checks PostgreSQL and Redis. Returns 503 only when PostgreSQL is unreachable. With only Redis down it returns 200 and `degraded`, so a Redis outage doesn't take every instance out of service.
         */
        get: operations["HealthController_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginBody: {
            /**
             * Format: email
             * @description Compared case-insensitively
             * @example customer@example.com
             */
            email: string;
            password: string;
        };
        CustomerMe_Output: {
            customer: {
                /** Format: uuid */
                id: string;
                email: string;
                displayName: string | null;
            };
            /** @description Set for a guest session, which can see this one ticket and nothing else */
            guestTicketId: string | null;
            /** @description Send this back in the X-CSRF-Token header on every POST, PUT, PATCH and DELETE */
            csrfToken: string;
        };
        SignupBody: {
            /**
             * Format: email
             * @description Compared case-insensitively
             * @example customer@example.com
             */
            email: string;
        };
        SignupCompleteBody: {
            /** @description The token from the emailed link */
            token: string;
            displayName: string;
            /** @description 12 to 128 characters */
            password: string;
        };
        GuestAccessRequestBody: {
            /**
             * Format: email
             * @description Compared case-insensitively
             * @example customer@example.com
             */
            email: string;
            /** @description The ticket reference from an earlier email, like DSD-000123 */
            reference: string;
        };
        GuestAccessExchangeBody: {
            /** @description The token from the emailed link */
            token: string;
        };
        StaffMe_Output: {
            agent: {
                /** Format: uuid */
                id: string;
                email: string;
                displayName: string;
                /** @enum {string} */
                role: "agent" | "supervisor" | "admin";
            };
            /** @description What this agent may do. The agent app shows controls from this list; the API enforces it regardless */
            permissions: ("ticket:read:any" | "ticket:reply" | "ticket:note:create" | "ticket:status:update" | "ticket:priority:update" | "ticket:assign" | "ticket:reassign:any" | "ticket:escalate" | "ticket:audit:read" | "customer:read" | "kb:read" | "kb:write" | "kb:publish" | "canned:use" | "canned:manage" | "report:view" | "user:read" | "user:manage" | "ai:suggestion:read" | "ai:suggestion:request" | "ai:suggestion:feedback")[];
            /** @description Send this back in the X-CSRF-Token header on every POST, PUT, PATCH and DELETE */
            csrfToken: string;
        };
        InviteCompleteBody: {
            /** @description The token from the emailed link */
            token: string;
            /** @description 12 to 128 characters */
            password: string;
        };
        Liveness_Output: {
            /** @constant */
            status: "ok";
        };
        Readiness_Output: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
            checks: {
                /** @enum {string} */
                database: "up" | "down";
                /** @enum {string} */
                redis: "up" | "down";
            };
        };
        ProblemDetails: {
            /** @description Problem type URI; `about:blank` when the HTTP status says it all */
            type: string;
            /** @description Short summary of the problem type */
            title: string;
            status: number;
            /** @description Explanation specific to this occurrence */
            detail?: string;
            /** @description The request path that produced the problem */
            instance?: string;
            /** @description Matches the X-Request-Id response header and the server logs */
            requestId: string;
            /** @description Present on validation problems: one entry per invalid field */
            errors?: {
                /** @description Dot-separated path to the invalid field; empty for the whole body */
                path: string;
                message: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    CustomerAuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMe_Output"];
                };
            };
            /** @description The body doesn't match its schema (`validation-error`), or an emailed link is unknown, expired or used (`invalid-token`) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The email or password is incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not sent from a trusted origin (`csrf-rejected`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too many attempts; `Retry-After` says when to try again (`rate-limited`) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The rate-limit store is unreachable, so the request is refused rather than allowed unlimited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CustomerAuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupBody"];
            };
        };
        responses: {
            /** @description Check your inbox */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The body doesn't match its schema (`validation-error`), or an emailed link is unknown, expired or used (`invalid-token`) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not sent from a trusted origin (`csrf-rejected`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too many attempts; `Retry-After` says when to try again (`rate-limited`) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The rate-limit store is unreachable, so the request is refused rather than allowed unlimited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CustomerAuthController_completeSignup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupCompleteBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMe_Output"];
                };
            };
            /** @description The body doesn't match its schema (`validation-error`), or an emailed link is unknown, expired or used (`invalid-token`) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not sent from a trusted origin (`csrf-rejected`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too many attempts; `Retry-After` says when to try again (`rate-limited`) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The rate-limit store is unreachable, so the request is refused rather than allowed unlimited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CustomerAuthController_requestGuestLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestAccessRequestBody"];
            };
        };
        responses: {
            /** @description Check your inbox */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The body doesn't match its schema (`validation-error`), or an emailed link is unknown, expired or used (`invalid-token`) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not sent from a trusted origin (`csrf-rejected`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too many attempts; `Retry-After` says when to try again (`rate-limited`) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The rate-limit store is unreachable, so the request is refused rather than allowed unlimited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CustomerAuthController_exchangeGuestLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestAccessExchangeBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMe_Output"];
                };
            };
            /** @description The body doesn't match its schema (`validation-error`), or an emailed link is unknown, expired or used (`invalid-token`) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not sent from a trusted origin (`csrf-rejected`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too many attempts; `Retry-After` says when to try again (`rate-limited`) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The rate-limit store is unreachable, so the request is refused rather than allowed unlimited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CustomerAuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session for this realm */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The Origin or the CSRF token was missing or wrong (`csrf-rejected`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CustomerAuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMe_Output"];
                };
            };
            /** @description No valid session for this realm */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    StaffAuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffMe_Output"];
                };
            };
            /** @description The body doesn't match its schema (`validation-error`), or an emailed link is unknown, expired or used (`invalid-token`) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The email or password is incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not sent from a trusted origin (`csrf-rejected`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too many attempts; `Retry-After` says when to try again (`rate-limited`) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The rate-limit store is unreachable, so the request is refused rather than allowed unlimited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    StaffAuthController_acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCompleteBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffMe_Output"];
                };
            };
            /** @description The body doesn't match its schema (`validation-error`), or an emailed link is unknown, expired or used (`invalid-token`) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not sent from a trusted origin (`csrf-rejected`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too many attempts; `Retry-After` says when to try again (`rate-limited`) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The rate-limit store is unreachable, so the request is refused rather than allowed unlimited */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    StaffAuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session for this realm */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The Origin or the CSRF token was missing or wrong (`csrf-rejected`) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    StaffAuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffMe_Output"];
                };
            };
            /** @description No valid session for this realm */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    HealthController_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness_Output"];
                };
            };
        };
    };
    HealthController_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready, or degraded without Redis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness_Output"];
                };
            };
            /** @description PostgreSQL is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness_Output"];
                };
            };
        };
    };
}
