/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/customer/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description Starts a new customer session in an HttpOnly cookie and returns the same body as `me`. A wrong password, an unknown email and a guest without a password all get the same 401.
         */
        post: operations["CustomerAuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/customer/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Revokes this session and clears its cookies.
         */
        post: operations["CustomerAuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/customer/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in customer
         * @description For a guest session, `guestTicketId` names the one ticket it can see.
         */
        get: operations["CustomerAuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/staff/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description Starts a new staff session in an HttpOnly cookie and returns the same body as `me`. A deactivated agent, or one who hasn't accepted their invite, gets the same 401 as a wrong password.
         */
        post: operations["StaffAuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/staff/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Revokes this session and clears its cookies.
         */
        post: operations["StaffAuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/staff/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in agent, with their role and permissions */
        get: operations["StaffAuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description The process is running and can answer. Checks no dependencies.
         */
        get: operations["HealthController_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Checks PostgreSQL and Redis. Returns 503 only when PostgreSQL is unreachable. With only Redis down it returns 200 and `degraded`, so a Redis outage doesn't take every instance out of service.
         */
        get: operations["HealthController_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginBody: {
            /**
             * Format: email
             * @description Compared case-insensitively, after trimming
             */
            email: string;
            password: string;
        };
        CustomerMe_Output: {
            customer: {
                /** Format: uuid */
                id: string;
                email: string;
                displayName: string | null;
            };
            /** @description Set for a guest session, which can see this one ticket and nothing else */
            guestTicketId: string | null;
            /** @description Send this back in the X-CSRF-Token header on every POST, PUT, PATCH and DELETE */
            csrfToken: string;
        };
        StaffMe_Output: {
            agent: {
                /** Format: uuid */
                id: string;
                email: string;
                displayName: string;
                /** @enum {string} */
                role: "agent" | "supervisor" | "admin";
            };
            /** @description What this agent may do. The agent app shows controls from this list; the API enforces it regardless */
            permissions: ("ticket:read:any" | "ticket:reply" | "ticket:note:create" | "ticket:status:update" | "ticket:priority:update" | "ticket:assign" | "ticket:reassign:any" | "ticket:escalate" | "ticket:audit:read" | "customer:read" | "kb:read" | "kb:write" | "kb:publish" | "canned:use" | "canned:manage" | "report:view" | "user:read" | "user:manage" | "ai:suggestion:read" | "ai:suggestion:request" | "ai:suggestion:feedback")[];
            /** @description Send this back in the X-CSRF-Token header on every POST, PUT, PATCH and DELETE */
            csrfToken: string;
        };
        Liveness_Output: {
            /** @constant */
            status: "ok";
        };
        Readiness_Output: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
            checks: {
                /** @enum {string} */
                database: "up" | "down";
                /** @enum {string} */
                redis: "up" | "down";
            };
        };
        ProblemDetails: {
            /** @description Problem type URI; `about:blank` when the HTTP status says it all */
            type: string;
            /** @description Short summary of the problem type */
            title: string;
            status: number;
            /** @description Explanation specific to this occurrence */
            detail?: string;
            /** @description The request path that produced the problem */
            instance?: string;
            /** @description Matches the X-Request-Id response header and the server logs */
            requestId: string;
            /** @description Present on validation problems: one entry per invalid field */
            errors?: {
                /** @description Dot-separated path to the invalid field; empty for the whole body */
                path: string;
                message: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    CustomerAuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMe_Output"];
                };
            };
        };
    };
    CustomerAuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomerAuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerMe_Output"];
                };
            };
        };
    };
    StaffAuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffMe_Output"];
                };
            };
        };
    };
    StaffAuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StaffAuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffMe_Output"];
                };
            };
        };
    };
    HealthController_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness_Output"];
                };
            };
        };
    };
    HealthController_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready, or degraded without Redis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness_Output"];
                };
            };
            /** @description PostgreSQL is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness_Output"];
                };
            };
        };
    };
}
