/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description The process is running and can answer. Checks no dependencies.
         */
        get: operations["HealthController_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Checks PostgreSQL and Redis. Returns 503 only when PostgreSQL is unreachable. With only Redis down it returns 200 and `degraded`, so a Redis outage doesn't take every instance out of service.
         */
        get: operations["HealthController_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Liveness_Output: {
            /** @constant */
            status: "ok";
        };
        Readiness_Output: {
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
            checks: {
                /** @enum {string} */
                database: "up" | "down";
                /** @enum {string} */
                redis: "up" | "down";
            };
        };
        ProblemDetails: {
            /** @description Problem type URI; `about:blank` when the HTTP status says it all */
            type: string;
            /** @description Short summary of the problem type */
            title: string;
            status: number;
            /** @description Explanation specific to this occurrence */
            detail?: string;
            /** @description The request path that produced the problem */
            instance?: string;
            /** @description Matches the X-Request-Id response header and the server logs */
            requestId: string;
            /** @description Present on validation problems: one entry per invalid field */
            errors?: {
                /** @description Dot-separated path to the invalid field; empty for the whole body */
                path: string;
                message: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness_Output"];
                };
            };
        };
    };
    HealthController_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready, or degraded without Redis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness_Output"];
                };
            };
            /** @description PostgreSQL is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness_Output"];
                };
            };
        };
    };
}
